export const BASE_ELEMENT = {
    'inpurt': '输入框',
    'textarea': '多行文本框',
    'button': '按钮',
    'checkbox': '复选框',
    'radio': '单选框',
    'label': '标签',
    'link': '链接',
    'image': '图片',
    'video': '视频',
    'audio': '音频',
    'table': '表格',
    'form': '表单',
    'upload': '上传',
}