
export default{
    click:{
        sescriptions:"点击事件",
        type:"click",
    },
    change:{
        sescriptions:"输入框内容变化事件",
        type:"change",
    },
    input:{
        sescriptions:"输入事件",
        type:"input",
    },
    focus:{
        sescriptions:"聚焦事件",
        type:"focus",
    },
    blur:{
        sescriptions:"失焦事件",
        type:"blur",
    },
    mouseover:{
        sescriptions:"鼠标移入事件",
        type:"mouseover",
    },
    mouseout:{
        sescriptions:"鼠标移出事件",
        type:"mouseout",
    },
    mouseenter:{
        sescriptions:"鼠标进入事件",
        type:"mouseenter",
    },
    mouseleave:{
        sescriptions:"鼠标离开事件",
        type:"mouseleave",
    },
    submit:{
        sescriptions:"提交事件",
        type:"submit",
    },
    keyup:{
        sescriptions:"键盘按下事件",
        type:"keyup",
    },
    keydown:{
        sescriptions:"键盘按下事件",
        type:"keydown",
    },
    keypress:{
        sescriptions:"键盘按下事件",
        type:"keypress",
    },
    resize:{
        sescriptions:"窗口大小变化事件",
        type:"resize",
    },
    scroll:{
        sescriptions:"滚动事件",
        type:"scroll",
    },
    copy:{
        sescriptions:"复制事件",
        type:"copy",
    },
    message:{
        sescriptions:"消息事件",
        type:"message",
    },
    toggle:{
        sescriptions:"复选框状态变化事件",
        type:"toggle",
    },
    wheel:{
        sescriptions:"滚轮事件",
        type:"wheel",
    },
}